### ISSUE TITLE
Maintenance Overview: List MVC packages in a separate column/block

### ISSUE THREAD

**Issue by froschdesign** [laminas/getlaminas.org#190]
The current overview lists the components and the MVC packages in a column/block but the MVC packages should be listed in an own column/block, like we have in the documentation:

- https://docs.laminas.dev
- https://docs.laminas.dev/mvc/
- and in the footer of the website and documentations

**Comment by arhimede** [comment]
Currently the list of components are retrieved based on org name: laminas, mezzio, api-tools.
In order to have a separate block for MVC only , we will need to have a hardcoded filter list. 
Not a problem :-)

**Comment by arhimede** [comment]
![image](https://github.com/user-attachments/assets/d6e0a6df-f1b4-4673-912b-da2cfb0702c1)

**Comment by froschdesign** [comment]
@arhimede 
> I have the PR which address this ready , I prefer to see the previous PR merged first then to do a separate one.

If you follow the [contributing guidelines](https://github.com/laminas/.github/blob/5e7024ad2f9ac03fd187ec0497282b950424c835/CONTRIBUTING.md#working-on-a-patch) then you can create several pull requests in parallel. 😉 
[The content of the blog article is wrong if a new column/block is added.](https://github.com/laminas/getlaminas.org/pull/189#discussion_r1694226444)
