### ISSUE TITLE
redirect with 301 the non-existing routes

### ISSUE THREAD

**Issue by arhimede** [laminas/getlaminas.org#191]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | x.y.z

#### Summary

https://getlaminas.org/about/%C2%A0
Indexed in google SERP

#### Current behavior

display error message 

#### Expected behavior

redirect with 301 to index page

**Comment by froschdesign** [comment]
"301 - Moved Permanently" for not existing pages?

https://getlaminas.org/404

**Comment by arhimede** [comment]
> "301 - Moved Permanently" for non-existing pages?

Yes, as there are few non-existing pages already indexed in google, and we need them removed from there.

So either a 301 redirect to index 
OR a 404 blank no-content page

**Comment by froschdesign** [comment]
If the page does not exist, then 404. (What did not exist before cannot be moved afterwards. 😉)

---

I suggest a nice and funny 404 page. 😃

**Comment by Ocramius** [comment]
It's more about directing pre-existing search results to the right ones: aliases, if you wish to call them that.

**Comment by Xerkus** [comment]
Good. Crash and burn and fix promptly

**Comment by arhimede** [comment]
there is a quick fix for getlaminas.org codebase , but will not address the main issue, which is in mezzio-helpers 
https://github.com/mezzio/mezzio-helpers/blob/5.17.x/src/UrlHelper.php#L157

Will be a PR at mezzio-helpers soon
