### ISSUE TITLE
[RFC]: Add instuctions on how to submit blog entries

### ISSUE THREAD

**Issue by visto9259** [laminas/getlaminas.org#197]
## RFC

| Q                   | A      |
| ------------------- | ------ |
| Proposed Version(s) | N/A  |
| BC Break?           | No |

### Goal

- Provide instructions for a contibutor to add a blog post entry

### Background

Blog posts should be used more often to make announcements on new packages, major releases, TSC decisions, nominations, etc.

The maintainer of repo, or any contributor, should have instructions on how to do so.

### Proposal(s)

- Add instructions in a `ADD_BLOG_ENTRY.md` file in the repo's root. Instructions on where to add the file, add an author file, required content of md file, in addtion to the usual contribution instructions (fork, modify, test, PR)
- Add a link to that file in the README fle
- Add a link in the website itself (?)

**Comment by arhimede** [comment]
@visto9259 we have a PR about that . 
Do you think more instructions are needed ?

**Comment by visto9259** [comment]
I added comments in the PR

**Comment by arhimede** [comment]
solved in #221
