### ISSUE TITLE
Extend linting to all .md files ?

### ISSUE THREAD

**Issue by arhimede** [laminas/getlaminas.org#222]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes

#### Summary

Currently , the blog .md files and authors.md files are not checked.
Do we want to extend the check to all .md files ?

**Comment by froschdesign** [comment]
We should definitely do this!

---

The rule for checking the line length must be ignored:

`.markdownlint.json`
```json
{
    "default": true,
    "MD013": false
}
```

**Comment by arhimede** [comment]
@Xerkus any idea why the continuous integration is running linting only on README file ?
example this one 
https://github.com/laminas/getlaminas.org/actions/runs/11499789946/job/32008552667

**Comment by gsteel** [comment]
The CI action has 1 job for the readme and 1 job for anything in `/doc` or `/docs` - it'd be better to run the linter in a specific job here using a standalone action such as https://github.com/marketplace/actions/markdownlint-cli2-action
