### ISSUE TITLE
docs.laminas.dev yields 404

### ISSUE THREAD

**Issue by Sandman83** [laminas/getlaminas.org#25]
### Bug Report

The documentation link on the getlaminas.org website is broken and yields 404. 

|    Q        |   A
|------------ | ------
| Version(s)  | x.y.z

#### Summary

see above. 

#### Current behavior

see above.

#### How to reproduce

click on the documentation link in the ressources section on the website. 

#### Expected behavior

some docs to see...

**Comment by michalbundyra** [comment]
Works for me. Are you using some odd DNS servers? Can you open any *.dev domain? Maybe you have configured them to be local?

**Comment by Sandman83** [comment]
Ok... sorry for the noise and thanks for the hint. 
https://superuser.com/a/1413487
