### ISSUE TITLE
Laminas security PGP key not available

### ISSUE THREAD

**Issue by alexdenvir** [laminas/getlaminas.org#34]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | n/a

#### Summary

While randomly browsing the getlaminas.org site, I discovered that the PGP key for reporting sensitive vulnerabilities is unavailable.

Please note that this was discovered while randomly browsing. **I have not found a security vulnerability, so there is no need to panic**

#### Current behavior

Clicking the "[our PGP key](https://getlaminas.org/asset/laminas-security.asc)" link on the [Security](https://getlaminas.org/security/) page gives a 404 error

#### How to reproduce

Click the "our PGP key" link on the security page

#### Expected behavior

The contents of the PGP key should be displayed, or the file should be downloaded

**Comment by michalbundyra** [comment]
@alexdenvir Thanks for reporting, we will fix it as soon as possible. 👍
