### ISSUE TITLE
Security feed ends with server error 500

### ISSUE THREAD

**Issue by froschdesign** [laminas/getlaminas.org#39]
#### Current behavior

* Server error 500
* wrong layout for error message

#### How to reproduce

https://getlaminas.org/security/feed

#### Expected behavior

Outputs XML for feed.

**Comment by weierophinney** [comment]
I have a fix for the server error in #40.

When you say "wrong layout for error message", I'm not sure what you mean; we have exactly one layout (`layout::default`), and it's the one used by the `error:error` template. Could you elaborate? And might that be a separate issue entirely?
