### ISSUE TITLE
Building fails due to missing .env file

### ISSUE THREAD

**Issue by caseyw** [laminas/getlaminas.org#5]
I followed the readme testing directions to build and received the following error:

> ERROR: Couldn't find env file: /home/development/projects/getlaminas.org/.env

**Comment by bu3tt1** [comment]
.env seems not be used. It's possible to remove it from docker-compose.yml.
Unfortunately after removing it there are other problems to be solved, see https://github.com/laminas/getlaminas.org/issues/4

**Comment by weierophinney** [comment]
It's been removed at this point.
