### ISSUE TITLE
RFC - Support for Composer v2

### ISSUE THREAD

**Issue by asgrim** [laminas/getlaminas.org#71]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary

I tried setting up the project, only to find it requires the use of Composer v1.

I am happy to attempt an upgrade, but I do not know what the production infra has, therefore I am unable to guarantee things will not break on deployment.

Also need to check if `laminas/laminas-dependency-plugin` has support for Composer v2:

```
laminas/laminas-dependency-plugin[1.0.3, ..., 1.0.4] require composer-plugin-api ^1.1
```

**Comment by rieschl** [comment]
> I am happy to attempt an upgrade, but I do not know what the production infra has, therefore I am unable to guarantee things will not break on deployment.

As long as you don't _require_ Composer 2, what can break? 😛 

> Also need to check if `laminas/laminas-dependency-plugin` has support for Composer v2:

[laminas/laminas-dependency-plugin v2](https://github.com/laminas/laminas-dependency-plugin/releases/tag/2.0.0) has Composer 2 support.

**Comment by asgrim** [comment]
> As long as you don't _require_ Composer 2, what can break? 😛 
> 

If the prod env has Composer 1, then deploying a Composer 2 format lock file would break, I think? That's an assumption of mine, I've never actually verified it tbh.

Additionally, if we upgrade the Laminas dep above, that would require Composer 2 in prod (or deploy) anyway. I have no idea what the deploys are like for this do maybe @weierophinney could confirm?

**Comment by boesing** [comment]
@asgrim `laminas/laminas-dependency-plugin` v2 has support for both composer v1 and v2.

**Comment by arueckauer** [comment]
This should be solved.

https://github.com/laminas/getlaminas.org/blob/master/composer.lock#L6515

**Comment by Ocramius** [comment]
Indeed, closing as per https://github.com/laminas/getlaminas.org/blob/4556ac2f60256ac1b977d6a1a05093e15f521296/composer.lock#L6515
